# Generated by Django 4.1.5 on 2023-01-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sekolah',
            name='jenis_sekolah',
        ),
        migrations.RemoveField(
            model_name='sekolah',
            name='web',
        ),
        migrations.AddField(
            model_name='sekolah',
            name='fax',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='kabupaten_kota',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='kecamatan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='npsn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='provinsi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='status',
            field=models.CharField(choices=[('NGR', 'Negeri'), ('SWST', 'Swasta')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='alamat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='nama',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='no_tlp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
