# Generated by Django 4.1.5 on 2023-01-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
        ('siswa', '0002_delete_sekolah_alter_siswa_jenis_kelamin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='asal_sekolah',
        ),
        migrations.AddField(
            model_name='siswa',
            name='sekolah',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah', verbose_name='sekolah siswa'),
        ),
    ]
