# Generated by Django 4.1.5 on 2023-01-16 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
        ('siswa', '0003_remove_siswa_asal_sekolah_siswa_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah'),
        ),
    ]
