# Generated by Django 4.1.5 on 2023-01-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_sekolah_created_by'),
        ('siswa', '0006_siswa_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah'),
        ),
    ]
