# Generated by Django 4.1.5 on 2023-01-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_sekolah_created_by'),
        ('siswa', '0007_alter_siswa_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='sekolah',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah'),
        ),
    ]
