# Generated by Django 4.1.5 on 2023-01-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='jenis_perusahaan',
            field=models.CharField(choices=[('PT', 'Persero Terbatas (PT)'), ('CV', 'Persekutuan Komanditer (CV)'), ('FMA', 'Firma'), ('KPR', 'Koperasi'), ('YYS', 'Yayasan')], max_length=3),
        ),
    ]
