# Generated by Django 4.1.5 on 2023-01-18 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perusahaan', '0002_alter_perusahaan_jenis_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perusahaan_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
