# Generated by Django 4.1.5 on 2023-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0003_perusahaan_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perusahaan',
            name='jenis_perusahaan',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='web',
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='bidang',
            field=models.CharField(blank=True, choices=[('PE', 'Perusahaan Ekstraktif'), ('PA', 'Perusahaan Agraris'), ('PD', 'Perusahaan Dagang'), ('PJ', 'Perusahaan Jasa'), ('PI', 'Perusahaan Industri')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('KBTU', 'Kabag TU')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='kategori',
            field=models.CharField(choices=[('Pem', 'Pemerintahan'), ('Neg', 'Negeri')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='nama_pic',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
